# Generated by Django 5.0.7 on 2024-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
