# Generated by Django 5.0.7 on 2024-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracker', '0002_task_xp_alter_task_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='xp',
        ),
    ]
